spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 150000
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/a_001_yaodian_man_sys?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: root@123
  servlet:
    multipart:
      max-file-size: 1000000000
      max-request-size: 100000000
  mvc: #静态文件
    static-path-pattern: /static/**
  #模板引擎
  thymeleaf:
    model: HTML5
    prefix: classpath:/templates/
    suffix: .html
    #指定编码
    encoding: utf-8
    #禁用缓存 默认false
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapperLocations: classpath*:mapper/*.xml


logging:
  level:
    com: debug

server:
  port: 60030


aliyun:
  file:
    endpoint: http://oss-cn-beijing.aliyuncs.com
    ### key
    accessKeyId: LTAI4GEa1G1VWDELTadpL8Ng
    ### 密钥
    accessKeySecret: s6Hy3B32HgdmJqJa3KrRiWTC2wSFdY
    ### 每一个存储对象都有一个
    bucketName: study-test-dd
    ### 用于在浏览器中页面的访问 类比 a标签中href的数据
    webUrl: https://study-test-dd.oss-accelerate.aliyuncs.com/


